image: 
envSecret: 
storage:
  enabled: false
  path: /srv/http/storage/app
app:
  replicas: 1
  upPath: /up
  # podLabels:
  ingress:
    host: 
    path: /
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt"
      traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
  command: "web"
  autoscaling:
    enabled: false
   #  minReplicas: 1
   #  maxReplicas: 100
   #  targetCPUUtilizationPercentage: 80
   #  targetMemoryUtilizationPercentage: 80

queue:
  enabled: true
  replicas: 1
  command: "queue"
#  podLabels:
cron:
  enabled: true
  command: "schedule"

