---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "laravel.name" . }}-migration
spec:
  template:
    spec:
      containers:
        - name: cron
          image: {{ .Values.image }}
          imagePullPolicy: IfNotPresent
          command:
          - /usr/bin/php
          - /srv/http/artisan
          - migrate
          envFrom:
            - secretRef:
                name: {{ .Values.env-secret }}
      restartPolicy: Never
