---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "laravel.name" . }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "laravel.name" . }}