---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "laravel.name" . }}
  {{- with .Values.app.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: {{ .Values.app.ingress.host }}
      http:
        paths:
        - backend:
            service:
              name: {{ include "laravel.name" . }}
              port:
                name: http
          path: {{ .Values.app.ingress.path }}
          pathType: Prefix
  tls:
    - hosts:
        - {{ .Values.app.ingress.host }}
      secretName: {{ include "laravel.name" . }}-tls